import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Footer } from "@/components/footer/footer";
import { UserNavbar } from "@/components/navbar/userNavbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "HuBeing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>
        <UserNavbar />
        <div className="relative flex h-auto min-h-screen w-full flex-col bg-[#112217] dark group/design-root overflow-x-clip">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
